Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,5 +11,7 @@ jobs:
 
     - name: Run a simple github action
       run: echo "this workflow is running with success, for this particular action"
-        
+
+    - name: Simulating error
+      run: echo "error talkin place"; exit 1
       
